### ISSUE TITLE
MaaColony-Across all the Mobile Application - Common issues

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#10]
Issue-1: Please provide commas for Amount values across the application.
Issues-2: Remove time stamp from Dates across the application.

**Comment by ijazakram** [comment]
We have added a comma for the amount in the applications.
And on some screens, we have given time stamp its good not odd.
And we have a good % of space in the mobile app.

thanks

**Comment by ijazakram** [comment]
We have added a comma for the amount in the applications.
And on some screens, we have given time stamp its good not odd.
And we have a good % of space in the mobile app.


--- for this reason, I am making as RESOLVED.
thanks

**Comment by FayazMaacolony** [comment]
Issue-1: Not Resolved. Payment screen: 
Payment Info tab - Sum totals didn't have commas
Payment Receipt tab - Doesn't have commas
Issues-2: Remove time stamp from Dates across the application.-Comparatively web it is matching hence closed
