### ISSUE TITLE
MaaColony-User Profile-couple of Issues

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#11]
Issue-1: Able to  view Email ID twice on User Profile screen.
Issue-2: Unable to view House information under "House Details" tab for few Houses.
Issue-3: Provide Role name of the logged in user.
Issue-4: Two dates on User Profile, Provide labels for Start Date and End Date under "Owner Information". and under "House Information" please provide labels as "Begin Date" and "End Date".
Issue-5: Vehicle Information - Please provide Add, Edit and Delete icons.
Issue-6: Able to view Role names under "Member Type" drop down box. It should display below Member types:
   a. Owner
   b. Tennant
  c. Builder
Issue-7: Please provide picker or drop down box for Country Code where ever it is applicable.
Ex: Edit User Profile

**Comment by Rajeswari06** [comment]
Open Issues:

Issue-1: Able to view Email ID twice on User Profile screen.
Issue-3: Provide Role name of the logged in user.

**Comment by ijazakram** [comment]
<Fayaz>Issue-1: Able to view Email ID twice on the User Profile screen.
<Akram> Its style of quick design from the Designer. I think it's OK.

<Fayaz>Issue-3: Provide Role name of the logged in user.
@Rajeswari06 Please fix as per our discussions in the API end. If U have any API based issues, please update here.

**Comment by FayazMaacolony** [comment]
Not able to view Role name on My Profile screen

**Comment by Rajeswari06** [comment]
@ijazakram please provide an update on this
