### ISSUE TITLE
Able to view blank screen when I returned from Receipts tab under Payment Screen

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#13]
Able to view blank screen when I returned from Receipts tab under Payment Screen

**Comment by FayazMaacolony** [comment]
![Able to view blank screen when I returned from Reciepts tab under Payment Screen](https://user-images.githubusercontent.com/51132032/60754187-0a4df680-9ffb-11e9-8a66-d2bd137fffb7.jpg)

**Comment by ijazakram** [comment]
Resolved.

**Comment by FayazMaacolony** [comment]
Now it is working fine hence closed
