### ISSUE TITLE
User Profile-User should be able to upload a Photo

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#19]
User Profile-User should be able to upload a Photo

**Comment by FayazMaacolony** [comment]
![User Profile-User should be able to upload a Photo](https://user-images.githubusercontent.com/51132032/60754160-b6431200-9ffa-11e9-907b-b705078617dc.jpg)

**Comment by Rajeswari06** [comment]
duplicate of 25

**Comment by RamanaKiran** [comment]
Its duplicate issue
