### ISSUE TITLE
User Profile-Existing Member Type should be retained upon Edit

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#21]
User Profile-Existing Member Type should be retained upon Edit

**Comment by FayazMaacolony** [comment]
![User Profile-Existing Member Type should be retained upon Edit](https://user-images.githubusercontent.com/51132032/60754074-a5de6780-9ff9-11e9-99d9-381662fd33cf.jpg)

**Comment by RamanaKiran** [comment]
Member Type should not be even displayed as Editable field in User profile. This is calculated field (readonly field) which is determined by the status of the houses to which he is mapped

**Comment by ijazakram** [comment]
As per our Skype discussions, 
We never display member type for now @ version 1.0.
The current approach is fine for view / edit of profile.
