### ISSUE TITLE
Expenses screen: Alignment issue- Data is not displaying in single lines

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#34]
Expenses screen: Alignment issue- Data is not displaying in single lines

**Comment by Rajeswari06** [comment]
Please provide more information on this.

**Comment by ijazakram** [comment]
@FayazMaacolony Its good to share screen shorts for better understanding...
Please cross check again and share the images.
Mostely we never satisfy all devices co-ordinates...
For this reason, we are RESOLVED this issue.

**Comment by FayazMaacolony** [comment]
Working as expected hence closed
