### ISSUE TITLE
Reports: Issues on Mobile App

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#4]
Issue -1: Reports - All reports must have ability to download. So please place download icon.
Issue-2: Reports - Community Expenses: Report box is highlighted when we swap between Reports.
Issue-3: Reports - Community Expenses: Inconsistency while displaying data for "Expenditure Report" and "Monthly account Statement"
Issue-4: Reports-Maintenance: Filter to pick up date is not working when I select a date and it is not closing the filter and not navigating back to Maintenance reports screen accordingly.
Issue-5: Reports - Community Expenses: Should display only date picker to filter. Currently Filter is generalized for all Reports.
Issue-6: Reports - Remove white space between the Reports page when Zoom in.
Issue-7: Paginations and tool bars to be included.
Issue-8: Slide view and control scroll bars to be implemented.

**Comment by Rajeswari06** [comment]
Issue -1: Reports - All reports must have ability to download. So please place download icon. -Pending

**Comment by FayazMaacolony** [comment]
Issue -1: Reports - All reports must have ability to download. So please place download icon - **Not implemented**
Issue-4: Reports-Maintenance: Filter to pick up date is not working when I select a date and it is not closing the filter and not navigating back to Maintenance reports screen accordingly - **Date Calendar is not visible properly and avoid displaying dates for Reports. It needs only Month and Year.**
Issue-7: Paginations and tool bars to be included - **Able to view only few Tool Bars are available comparatively with Web application. and Pagination selection is not implemented**.

**Comment by FayazMaacolony** [comment]
Issue -1: Reports - All reports must have ability to download. So please place download icon - Not implemented
Issue-4: Reports-Maintenance: Filter to pick up date is not working when I select a date and it is not closing the filter and not navigating back to Maintenance reports screen accordingly - Date Calendar is not visible properly and avoid displaying dates for Reports. It needs only Month and Year.
Issue-7: Paginations and tool bars to be included - Able to view only few Tool Bars are available comparatively with Web application. and Pagination selection is not implemented.

**Comment by FayazMaacolony** [comment]
Issue-4: Reports-Maintenance: Filter to pick up date is not working when I select a date and it is not closing the filter and not navigating back to Maintenance reports screen accordingly - Date Calendar is not visible properly and avoid displaying dates for Reports. It needs only Month and Year. - **Only Month year should be displayed now I am able to view complete calender**
Issue-7: Pagination and tool bars to be included - Able to view only few Tool Bars are available comparatively with Web application. and Pagination selection is not implemented. - **Please implement Pagination selection**
