### ISSUE TITLE
MaaColony Mobile App-User Profile-Updated changes are not reflecting in User Profile

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#5]
Updated changes are not reflecting in User Profile

**Comment by FayazMaacolony** [comment]
Unable to save Profile, even after selecting Member type hence closing the issue.

**Comment by ijazakram** [comment]
@Rajeswari06 Including the above issues, we need to save country code dynamically & display country code in the phone section as dynamically. Please add this one also.

**Comment by RamanaKiran** [comment]
For Country Code list make use of the below API -

https://test.maacolony.com/api/GCMemberApi/GetCodeList/?codeListID=27

**Comment by Rajeswari06** [comment]
Duplicate of 79
