### ISSUE TITLE
The app is prompting for login with Google/Facebook when ever I open the mobile app.I think it should not be the case unless I sign out explicitly(as we don't have sign out it should not ask till we implement) 

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#52]
The app is prompting for login with Google/Facebook when ever I open the mobile app.I think it should not be the case unless I sign out explicitly(as we don't have sign out it should not ask till we implement)

**Comment by ijazakram** [comment]
I think its resolved.
Please confirm QA team.

**Comment by FayazMaacolony** [comment]
Now it is working fine
