### ISSUE TITLE
In Maintenance tab -> On click of Filter option, it is showing up nothing i.e. no option to choose Monthly/OneTime 

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#54]
In Maintenance tab -> On click of Filter option, it is showing up nothing i.e. no option to choose Monthly/OneTime

**Comment by Rajeswari06** [comment]
check this in latest build, it depend's on Role

**Comment by FayazMaacolony** [comment]
Now I am able to see monthly and one Time
