### ISSUE TITLE
In Reports tab -> Only Monthly maintenance and Expenditure Reports are shown 

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#55]
In Reports tab -> Only Monthly maintenance and Expenditure Reports are shown

**Comment by Rajeswari06** [comment]
check this in latest build

**Comment by FayazMaacolony** [comment]
Now I am able to view
Maintenance - Monthly and One Time
Community Expenses - Expenses Report, monthly Account Statement and Account Summary hence closed
