### ISSUE TITLE
In Issue Management -> Edit Issue record -> Once the issue is raised, most of the fields are readonly and should not be edited (please refer to web app for the reference)

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#71]
In Issue   Management -> Edit Issue record -> Once the issue is raised, most of   the fields are readonly and should not be edited (please refer to web app for   the reference)
--

**Comment by Rajeswari06** [comment]
Requested date is un editable. @ijazakram  please let me know what other fields are un editable.
